DROP TABLE IF EXISTS CAMPAIGN;

CREATE TABLE CAMPAIGN (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  start_date DATE NOT NULL,
  category VARCHAR(250) NOT NULL,
  bid DECIMAL NOT NULL
);
